ChauThienCuong_PetShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChauThienCuong_PetShop.Models;
using ChauThienCuong_PetShop.Context;


namespace ChauThienCuong_PetShop.Controllers
{
    public class CartController : Controller
    {
        PetShopEntities obj = new PetShopEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = obj.Product.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = obj.Product.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.id.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.id == id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

ChauThienCuong_PetShop/Controllers/ProductController.cs
using ChauThienCuong_PetShop.Context;
using ChauThienCuong_PetShop.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChauThienCuong_PetShop.Controllers
{
    public class ProductController : Controller
    {
        PetShopEntities obj = new PetShopEntities();
        // GET: Product
        public ActionResult Index(string searchString)
        {

            var listProduct = obj.Product.ToList();
            if (!string.IsNullOrEmpty(searchString))
            {
                // Chuyển chuỗi tìm kiếm về chữ thường
                string searchLower = searchString.ToLower();
                // Lọc danh sách danh mục theo chuỗi tìm kiếm chữ thường
                listProduct = listProduct.Where(c =>
                    c.name.ToLower().Contains(searchLower)).ToList();
            }
            return View(listProduct);
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var objProduct = obj.Product.Where(n => n.id == id).FirstOrDefault();
            return View(objProduct);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(obj.Category, "id", "name");
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(Product pro, HttpPostedFileBase uploadhinh)
        {
            obj.Product.Add(pro);

            obj.SaveChanges();

            if (uploadhinh != null && uploadhinh.ContentLength > 0)
            {
                int id = int.Parse(obj.Product.ToList().Last().id.ToString());

                string _FileName = Path.GetFileName(uploadhinh.FileName);
                int index = uploadhinh.FileName.IndexOf('.');
                string _path = Path.Combine(Server.MapPath("~/Context/images/productImage"), _FileName);
                uploadhinh.SaveAs(_path);

                Product unv = obj.Product.FirstOrDefault(x => x.id == id);
                unv.image = _FileName;
                obj.SaveChanges();
            }


            return RedirectToAction("Index");
        }
        // GET: Product/Edit/5
        // GET: Product/Edit/5
        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            // Lấy sản phẩm từ cơ sở dữ liệu bằng id
            Product pro = obj.Product.FirstOrDefault(x => x.id == id);

            // Lấy danh sách các danh mục sản phẩm từ cơ sở dữ liệu và gán cho ViewBag.Categories
            ViewBag.Category = new SelectList(obj.Category, "id", "name");

            // Gán giá trị cũ của category_id cho ViewBag để sử dụng trong view
            ViewBag.CurrentCategory = pro.category_id;

            return View(pro);
        }


        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(Product pro, HttpPostedFileBase uploadhinh)
        {
            // Lấy sản phẩm từ cơ sở dữ liệu dựa trên ID
            Product unv = obj.Product.FirstOrDefault(x => x.id == pro.id);
            if (unv == null)
            {
                return HttpNotFound(); // Hoặc xử lý lỗi khác tùy vào yêu cầu của ứng dụng
            }

            // Cập nhật thông tin sản phẩm
            unv.name = pro.name;
            unv.price = pro.price;
            unv.descreption = pro.descreption;
            unv.category_id = pro.category_id; // Cập nhật category_id

            // Xử lý tập tin ảnh
            if (uploadhinh != null && uploadhinh.ContentLength > 0)
            {
                // Xử lý tập tin ảnh
                string _FileName = Path.GetFileName(uploadhinh.FileName);
                string _path = Path.Combine(Server.MapPath("~/Context/images/productImage"), _FileName);
                uploadhinh.SaveAs(_path);
                unv.image = _FileName;
            }

            // Lưu thay đổi vào cơ sở dữ liệu
            obj.SaveChanges();

            return RedirectToAction("Index");
        }


        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            var objProduct = obj.Product.Find(id);
            return View(objProduct);
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var productToDelete = obj.Product.Find(id);

                obj.Product.Remove(productToDelete);

                obj.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GetAllProducts()
        {
            HomeModel objHomeModel = new HomeModel();
            objHomeModel.ListCategory = obj.Category.ToList();
            objHomeModel.ListProduct = obj.Product.ToList();
            return View(objHomeModel);
        }

    }
}

ChauThienCuong_PetShop/Views/Product/Create.cshtml
@model ChauThienCuong_PetShop.Context.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descreption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.descreption, new { @class = "form-control", @rows = 4 })
            @Html.ValidationMessageFor(model => model.descreption, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.category_id, (SelectList)ViewBag.Category, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <input type="file" id="uploadhinh" name="uploadhinh" accept="image/*" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ChauThienCuong_PetShop/Views/Product/Delete.cshtml
@model ChauThienCuong_PetShop.Context.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descreption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descreption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChauThienCuong_PetShop/Views/Product/Details.cshtml
@model ChauThienCuong_PetShop.Context.Product

@{
    ViewBag.Title = "Details";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#addtocart").click(function () {
            var model = {};
            // Lấy id sản phẩm
            model.Id = @Model.id;
            // Lấy số lượng đặt hàng
            var quantity = $("#ipQuantity").val();
            // Kiểm tra số lượng phải lớn hơn 0
            if (quantity > 0) {
                model.Quantity = quantity;
                debugger;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("AddToCart", "Cart")',
                    data: JSON.stringify(model),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function () {
                        alert("Thêm giỏ hàng thành công!")
                        $('#CartCount').text(@Session["count"] + 1);
                    },
                    error: function () {
                        alert("Lỗi trong khi thêm vào giỏ hàng!");
                    }
                });
            } else {
                alert("Số lượng phải lớn hơn 0!");
            }
            return false;
        });
    });
</script>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
    <div class="container">

        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div>
                                <a href="#">
                                    <img src="~/Context/images/productImage/@Model.image">
                                </a>
                            </div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </div> <!-- card.// -->
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">

                    <h2 class="title mt-3">@Model.name </h2>

                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width:80%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">132 reviews</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders </small>
                    </div> <!-- rating-wrap.// -->

                    <div class="mb-3">
                        @{
                            string formattedPrice = string.Format("{0:N0}", Model.price);
                        }
                        <var class="price h4">@formattedPrice đ</var>

                    </div> <!-- price-detail-wrap .// -->

                    <p>
                        @Model.descreption
                    </p>


                    <div class="form-row  mt-4">
                        <div class="form-group col-md flex-grow-0">
                            <div class="input-group mb-3 input-spinner">
                                <input type="text" id="ipQuantity" class="form-control" value="1">
                            </div>
                        </div> <!-- col.// -->
                        <div class="form-group col-md">
                            <a href="#" id="addtocart" class="btn  btn-primary">
                                <i class="fas fa-shopping-cart"></i>
                                <span class="text" h>Thêm vào giỏ hàng</span>
                            </a>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->

                </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
        <!-- ================ ITEM DETAIL END .// ================= -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION  ========================= -->
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->

ChauThienCuong_PetShop/Views/Product/Edit.cshtml
@model ChauThienCuong_PetShop.Context.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @Value = Model.name } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", @Value = Model.price } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descreption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.descreption, new { @class = "form-control", @rows = 4, @Value = Model.descreption })
            @Html.ValidationMessageFor(model => model.descreption, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.category_id, (SelectList)ViewBag.Category, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img style="width: 100px; height: 100px;" src="~/Upload/productImage/@Model.image" />
            <input type="file" id="uploadhinh" name="uploadhinh" accept="image/*" />
            <a href="~/Views/Home/Contact.cshtml">~/Views/Home/Contact.cshtml</a>
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ChauThienCuong_PetShop/Views/Product/GetAllProducts.cshtml
@model ChauThienCuong_PetShop.Models.HomeModel

@{
    ViewBag.Title = "GetAllProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tất cả sản phẩm</h2>

<header class="mb-3">
    <div class="form-inline">
        <select class="mr-2 form-control">
            <option>Latest items</option>
            <option>Trending</option>
            <option>Most Popular</option>
            <option>Cheapest</option>
        </select>
        <div class="btn-group">
            <a href="page-listing-grid.html" class="btn btn-light active" data-toggle="tooltip" title="List view">
                <i class="fa fa-bars"></i>
            </a>
            <a href="page-listing-large.html" class="btn btn-light" data-toggle="tooltip" title="Grid view">
                <i class="fa fa-th"></i>
            </a>
        </div>
    </div>
</header><!-- sect-heading -->

<div class="row">
    @foreach (var item in Model.ListProduct)
    {
        <div class="col-md-3">
            <figure class="card card-product-grid">
                <div class="img-wrap">

                    <img src="@Url.Content("~/Context/images/productImage/" + item.image)">
                </div>
                <figcaption class="info-wrap">
                    <a href="@Url.Content("~/Product/Details/" + item.id)" class="title mb-2">@item.name</a>
                    <div class="price-wrap">
                        <span class="price">@string.Format("{0:C}", item.price)</span>
                        <small class="text-muted">/per item</small>
                    </div>



                </figcaption>
            </figure>
        </div> <!-- col.// -->
    }
</div> <!-- row end.// -->



<nav class="mb-4" aria-label="Page navigation sample">
    <ul class="pagination">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">4</a></li>
        <li class="page-item"><a class="page-link" href="#">5</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>


<div class="box text-center">
    <p>Did you find what you were looking for？</p>
    <a href="" class="btn btn-light">Yes</a>
    <a href="" class="btn btn-light">No</a>
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
    <div class="container">
        <section class="footer-top padding-y-lg text-white">
            <div class="row">
                <aside class="col-md col-6">
                    <h6 class="title">Brands</h6>
                    <ul class="list-unstyled">
                        <li> <a href="#">Adidas</a></li>
                        <li> <a href="#">Puma</a></li>
                        <li> <a href="#">Reebok</a></li>
                        <li> <a href="#">Nike</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Company</h6>
                    <ul class="list-unstyled">
                        <li> <a href="#">About us</a></li>
                        <li> <a href="#">Career</a></li>
                        <li> <a href="#">Find a store</a></li>
                        <li> <a href="#">Rules and terms</a></li>
                        <li> <a href="#">Sitemap</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Help</h6>
                    <ul class="list-unstyled">
                        <li> <a href="#">Contact us</a></li>
                        <li> <a href="#">Money refund</a></li>
                        <li> <a href="#">Order status</a></li>
                        <li> <a href="#">Shipping info</a></li>
                        <li> <a href="#">Open dispute</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Account</h6>
                    <ul class="list-unstyled">
                        <li> <a href="#"> User Login </a></li>
                        <li> <a href="#"> User register </a></li>
                        <li> <a href="#"> Account Setting </a></li>
                        <li> <a href="#"> My Orders </a></li>
                    </ul>
                </aside>
                <aside class="col-md">
                    <h6 class="title">Social</h6>
                    <ul class="list-unstyled">
                        <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                        <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                        <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                        <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                    </ul>
                </aside>
            </div> <!-- row.// -->
        </section>	<!-- footer-top.// -->

        <section class="footer-bottom text-center">

            <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
            <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
            <br>
        </section>
    </div><!-- //container -->
</footer>

ChauThienCuong_PetShop/Views/Product/Index.cshtml
@model IEnumerable<ChauThienCuong_PetShop.Context.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Product", FormMethod.Get))
{
    <div class="input-group mb-3" style="max-width: 300px;">
        <input type="text" name="searchString" class="form-control" placeholder="Tìm kiếm sản phẩm">
        <div class="input-group-append">
            <button type="submit" class="btn btn-outline-success">Search</button>
        </div>
    </div>

}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descreption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.category_id)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descreption)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category_id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>